### ISSUE TITLE
Download as TSV behavior not working as expected

### ISSUE THREAD

**Issue by albenson-usgs** [gbif/literature-ws#13]
We were attempting to use Download as TSV for the literature for the [United States Geological Survey publisher](https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=2e4967ed-fd35-4d34-ae4d-e8731d366e97) but it comes back blank. I wanted to confirm the behavior for other publishers. In some cases I receive a Network error ([example](https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=75bf5fec-40fa-43ae-919f-c43bd7ce25c9)) and in others it downloads fine ([example](https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=045f6b80-812c-11de-86fd-b8a03c50a862)). I believe it might be how many citations are associated with the publisher or dataset that causes either the network error or the blank TSV. For instance [iNaturalist dataset](https://www.gbif.org/resource/search?contentType=literature&gbifDatasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7) returns a blank TSV similar to USGS publisher.

**Comment by marcos-lg** [comment]
We were getting this error:

```
ERROR [2023-08-02 10:46:13,039+0000] [http-nio-9016-exec-23] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.io.IOException: entity content is too long [132383737] for the configured buffer limit [104857600]] with root cause
org.apache.http.ContentTooLongException: entity content is too long [132383737] for the configured buffer limit [104857600]
	at org.elasticsearch.client.HeapBufferedAsyncResponseConsumer.onEntityEnclosed(HeapBufferedAsyncResponseConsumer.java:76)
	at org.apache.http.nio.protocol.AbstractAsyncResponseConsumer.responseReceived(AbstractAsyncResponseConsumer.java:137)
	at org.apache.http.impl.nio.client.MainClientExec.responseReceived(MainClientExec.java:315)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseReceived(DefaultClientExchangeHandlerImpl.java:151)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:315)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(Thread.java:748)
```

I increased the buffer limit and it doesn't return blank files now.

The changes are deployed to production.
